### ISSUE TITLE
unable to build dockerfile

### ISSUE THREAD

**Issue by davejfranco** [lukaspustina/docker-registry#1]
I'm receiving this error message "Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
2015/03/02 20:56:25 The command [/bin/sh -c cd /docker-registry && pip install -r requirements.txt] returned a non-zero code: 1"

**Comment by lukaspustina** [comment]
Hi @davejfranco, you're right. Docker Registry has changed quite a lot since I built this repository. I already adapted the demo in https://github.com/lukaspustina/docker-registry-demo but forgot to change this image.
Please refer to the other repository. I'll fix this image once I'm back from my business trip.
